payment/core/urls.py
from django.urls import path
from . import views


app_name = "core"  



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.home, name='about'),
    path('contact/', views.home, name='contact')
]

payment/payment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("user_auth.urls")),  # Add this line
]

payment/user_auth/urls.py
from django.urls import path
from . import views

app_name = "user"  


urlpatterns = [
    path('sign-up', views.signUp, name='sign-up'),
    path('sign-in', views.signIn, name='sign-in'),
    path('sign-out', views.signOut, name='sign-out')
]

payment/core/models.py
from django.db import models

# Create your models here.

payment/user_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)


    USERNAME_FIELD = 'email' # to make sure that the email is used in place of the username
    REQUIRED_FIELDS = ['username', 'password']

    def __str__(self) -> str:
        return self.username

payment/user_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user_auth.models import User

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')

payment/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

def contact(request):
    return render(request, 'core/contact.html')

payment/user_auth/views.py
from django.shortcuts import render
from user_auth.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.
def signUp(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            messages.success(request, f"Hey {username}, your account was created successfully.")
            new_user = authenticate(username=email, password=password) 
            login(request, new_user)
            return render(request, "core/index.html")
    else:
        form = UserForm()
    if request.user.is_authenticated:
        messages.warning(request, f"{request.user.username}, you are already logged in. Log out to create a new account.")
        return render(request, "core/index.html")
    context = {
        "form": form
    }    
    return render(request, "user_auth/signup.html", context)

def signIn(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome back, {username}.")
            return render(request, "core/index.html")
        else:
            messages.error(request, "Invalid username or password.")
    return render(request, "core/index.html")

def signOut(request):
    logout(request.user)
    messages.success(request, "You have logged out successfully.")
    return render(request, "core/index.html")

payment/templates/core/about.html
{% extends "partials/base.html" %}
{% block content %}
    <p>About Page</p>

{% endblock %}

payment/templates/core/contact.html
<p>Contact Page</p>

payment/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Paylio - Money Transfer and Online Payments HTML Template</title>

        <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image/x-icon" />
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}" />
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    </head>

    <body>
        <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

        <header class="header-section">
            <div class="overlay">
                <div class="container">
                    <div class="row d-flex header-area">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <a class="navbar-brand" href="index.html">
                                <img src="{% static 'assets/images/logo.png' %}" class="logo" alt="logo" />
                            </a>
                            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-content">
                                <i class="fas fa-bars"></i>
                            </button>
                            <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
                                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                                    <li class="nav-item dropdown main-navbar">
                                        <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-bs-toggle="dropdown" data-bs-auto-close="outside">Personal</a>
                                        <ul class="dropdown-menu main-menu shadow">
                                            <li><a class="nav-link" href="payments-01.html">Freelancer Payments</a></li>
                                            <li><a class="nav-link" href="subscriptions.html">Subscriptions</a></li>
                                            <li><a class="nav-link" href="security.html">Security</a></li>
                                            <li><a class="nav-link" href="fees.html">Fees</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item dropdown main-navbar">
                                        <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-bs-toggle="dropdown" data-bs-auto-close="outside">Business</a>
                                        <ul class="dropdown-menu main-menu shadow">
                                            <li><a class="nav-link" href="payments-01.html">Business Payments</a></li>
                                            <li><a class="nav-link" href="business-account.html">Business Account</a></li>
                                            <li><a class="nav-link" href="corporate-card.html">Corporate Card</a></li>
                                            <li><a class="nav-link" href="expense-management.html">Expense Management</a></li>
                                            <li><a class="nav-link" href="budgeting-and-analytics.html">Budgeting</a></li>
                                            <li><a class="nav-link" href="integrations.html">Integrations</a></li>
                                            <li><a class="nav-link" href="invoice-management.html">Invoice</a></li>
                                            <li><a class="nav-link" href="security.html">Security</a></li>
                                            <li><a class="nav-link" href="rewards.html">Rewards</a></li>
                                            <li><a class="nav-link" href="fees.html">Fees</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item dropdown main-navbar">
                                        <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-bs-toggle="dropdown" data-bs-auto-close="outside">Company</a>
                                        <ul class="dropdown-menu main-menu shadow">
                                            <li><a class="nav-link" href="about-us.html">About Us</a></li>
                                            <li><a class="nav-link" href="career.html">Career</a></li>
                                            <li><a class="nav-link" href="career-details.html">Career Details</a></li>
                                            <li class="dropend sub-navbar">
                                                <a href="javascript:void(0)" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside">Blog</a>
                                                <ul class="dropdown-menu sub-menu shadow">
                                                    <li><a class="nav-link" href="blog.html">Blog</a></li>
                                                    <li><a class="nav-link" href="blog-details.html">Blog Details</a></li>
                                                </ul>
                                            </li>
                                            <li><a class="nav-link" href="error.html">Error</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item dropdown main-navbar">
                                        <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-bs-toggle="dropdown" data-bs-auto-close="outside">Help</a>
                                        <ul class="dropdown-menu main-menu shadow">
                                            <li><a class="nav-link" href="help-center.html">Help Center</a></li>
                                            <li><a class="nav-link" href="help-center-category.html">Help Category</a></li>
                                        </ul>
                                    </li>
                                </ul>
                                <div class="right-area header-action d-flex align-items-center max-un">
                                    <a href="{% url 'user:sign-in' %}" class="login">Login</a>
                                    <a href="{% url 'user:sign-up' %}" class="cmn-btn"
                                        >Sign Up
                                        <i class="icon-d-right-arrow-2"></i>
                                    </a>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </header>
        <!-- header-section end -->

        {% block content %} {% endblock content %}

        <!--==================================================================-->
        <script src="{% static 'assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/fontawesome.js' %}"></script>
        <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
        <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
        <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
        <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
        <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>

payment/templates/user_auth/signup.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
      <!-- Login Reg start -->
      <section class="login-reg">
        <div class="overlay pt-120">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-xl-6 order-xl-0 order-1">
                        <div class="sec-img d-rtl">
                            <img src="{% static 'assets/images/app-download-img.png' %}" class="max-un" alt="image">
                        </div>
                    </div>
                    <div class="col-xl-5">
                        <div class="section-text text-center">
                            <h5 class="sub-title">Account</h5>
                            <h2 class="title">Welcome to Paylio</h2>
                            <p class="dont-acc">Already have an account? <a href="{% url 'user:sign-in' %}">Login</a></p>
                            
                        </div>
                        <form method="POST">
                            {% csrf_token %}
                            <!-- <div class="alert-danger alert"> -->
                                <!-- More robust error viewer -->

                                <!-- {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <p> {{ error }} </p>
                                        {% endfor %}
                                    {% endfor %}
                                {% endif %} -->

                                <!-- Less robust error viewer -->
                                <!-- {% if form.errors %}
                                    <p> {{ form.errors }} </p>
                                {% endif %} -->
                            <!-- </div> -->
                            <div class="row">
                                <div class="col-12">
                                    <div class="single-input">
                                        <label for="{{ form.email.id_for_label }}">Email:</label>  
                                        {{form.email}}
                                    </div>
                                    <div class="single-input">
                                        <label for="{{ form.username.id_for_label }}">Username:</label>  
                                        {{form.username}}
                                    </div>
                                    <div class="single-input">
                                        <label for="{{ form.password1.id_for_label }}">Enter Password:</label>  
                                        {{form.password1}}
                                    </div>
                                    <div class="single-input">
                                        <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>  
                                        {{form.password2}}
                                    </div>
                                    <button class="cmn-btn w-100" type="submit">Sign Up</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Login Reg end -->
 {% endblock content %}